backend:
  name: github
  repo: YOUR_GITHUB_USERNAME/lamath8blog   # <-- THAY thành username của Lam
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Lang", name: "lang", widget: "select", options: ["vn","en"]}
      - {label: "Body", name: "body", widget: "markdown"}
